name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # 針對主分支的推送觸發工作流程

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: ''

      - name: Install dependencies
        run: ./mvnw clean install

      - name: Run tests
        run: ./mvnw test

      - name: Package application
        run: ./mvnw package

  deploy:
    runs-on: ubuntu-latest
    needs: build  # 等待 build 任務完成後執行

    steps:
      - name: Deploy to server
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # 套用固定的私鑰路徑，則刪除ex. /github/ssh/key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa # 將私鑰複製到預設位置
#           cp /github/ssh/key ~/.ssh/id_rsa  # 將私鑰複製到預設位置
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no $USER@$HOST '
            pkill -f myapp.jar || true;
            mkdir -p /var/www/myapp;
          '
          scp target/myapp.jar $USER@$HOST:/var/www/myapp
          ssh $USER@$HOST '
            cd /var/www/myapp && nohup java -jar myapp.jar > myapp.log 2>&1 &