name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # 針對主分支的推送觸發工作流程

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Install dependencies
        run: ./mvnw clean install

      - name: Run tests
        run: ./mvnw test

      - name: Package application
        run: ./mvnw package

  deploy:
    runs-on: ubuntu-latest
    needs: build  # 等待 build 任務完成後執行

    steps:
      - name: Deploy to server
        env:
          HOST: ${{ secrets.HOST }}        # 伺服器 IP 或域名
          USER: ${{ secrets.USER }}        # SSH 使用者
          PASSWORD: ${{ secrets.PASSWORD }} # SSH 密碼或金鑰
        run: |
          sshpass -p $PASSWORD ssh $USER@$HOST 'mkdir -p /var/www/myapp'
          sshpass -p $PASSWORD scp target/myapp.jar $USER@$HOST:/var/www/myapp
          sshpass -p $PASSWORD ssh $USER@$HOST 'cd /var/www/myapp && nohup java -jar myapp.jar &'
