name: CI/CD Pipeline

on:
  push:
    branches:
      - feature/*  # 自動觸發 `feature/` 開頭的分支推送事件
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to merge (default: feature/*)'
        required: true
        default: 'feature/release'  # 默認分支

jobs:
  auto-merge:
    strategy:
      matrix:
        servers: [ubuntu-latest, self-hosted]
    runs-on: ${{ matrix.servers }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Auto merge branch into main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin main
          git checkout main
          git merge --no-ff ${{ github.ref_name }}
          git push origin main

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'  # 或者你可以選擇 OpenJDK 這取決於需要

      - name: Install dependencies
        run: ./mvnw clean install

      - name: Run tests
        run: ./mvnw test

      - name: Package application
        run: ./mvnw package
